name: md
description: Basic Markdown formalization and string-renderer
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  freezed_annotation: ^2.1.0
  pure: ^0.2.0
  select_annotation: ^0.2.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  purple_lints: ^0.3.0
  select: ^0.3.1
  test: ^1.16.0
